<a href="https://colab.research.google.com/github/SantiagoGZ29/Proyectos-DUOC/blob/main/Formativa_S6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Ejercicio 1**:

Instrucciones específicas:
1.	Crea un arreglo unidimensional con nombre arregloA y de tamaño 100, con elementos aleatorios de números enteros del 0 al 500.
2.	Muestra por pantalla solo los valores que se encuentren en los índices pares del arreglo.
3.	Muestra el elemento mayor del arreglo.
4.	Muestra el índice (posición) del elemento mayor.
5.	Muestra el elemento menor del arreglo.
6.	Genera la copia de arreglo A y multiplicar por 3 cada elemento. Mostrar resultado.
7.	Muestra la suma de los elementos del segundo arreglo.
8.	Calcula el promedio de los elementos del segundo arreglo.

In [16]:
import random as rd
import numpy as np

#1
arregloA = np.random.randint(0, 501, size=100)
print("El arreglo inicial es: \n",arregloA)

#2
pares = arregloA % 2 == 0
numpares = arregloA[pares]
print("Los números pares son: \n",numpares)

#3
mayor = np.max(arregloA)
print("El número mayor es: \n",mayor)

#4
posmayor = np.where(arregloA == mayor)
print("La posición del número mayor es: \n",posmayor)

#5
menor = np.min(arregloA)
print("El número menor es: \n",menor)

#6
aregloB = arregloA.copy()
aregloB = aregloB * 3
print("El arreglo multiplicado por 3 es: \n",aregloB)

#7
suma = np.sum(aregloB)
print("La suma de los elementos del segundo arreglo es: \n",suma)


#8
promedio = np.mean(aregloB)
print("El promedio de los elementos del arreglo es: \n",promedio)



El arreglo inicial es: 
 [ 17 329  42 346  60 216 355 425 365 413 103  99 350 328 370 156 423 442
 152 150 412 397 398 108 237 318 352 152 195 227  98 176 302 350 399 413
 146 446 152 279  44 302 483 152 132  92 116 166 375 160 235 323 303 352
  82 366 311 221 422 286 480 182  36 276 260 427 386 488  51 275 136 157
  60 355  85 181  88 436 189 209  77 117 430 191 429 192 408 415 187 438
 482 465 166 498 259 285 396 142  77 465]
Los números pares son: 
 [ 42 346  60 216 350 328 370 156 442 152 150 412 398 108 318 352 152  98
 176 302 350 146 446 152  44 302 152 132  92 116 166 160 352  82 366 422
 286 480 182  36 276 260 386 488 136  60  88 436 430 192 408 438 482 166
 498 396 142]
El número mayor es: 
 498
La posición del número mayor es: 
 (array([93]),)
El número menor es: 
 17
El arreglo multiplicado por 3 es: 
 [  51  987  126 1038  180  648 1065 1275 1095 1239  309  297 1050  984
 1110  468 1269 1326  456  450 1236 1191 1194  324  711  954 1056  456
  585  681  294  528  906 1050 

**Ejercicio 2:**

Instrucciones específicas:
1.	Crea un arreglo unidimensional con nombre arreglo_1 y de tamaño 10, con elementos aleatorios de números enteros del 0 al 1000.
2.	Muestra por pantalla todos los elementos del arreglo.
3.	Cuenta los elementos pares.
4.	Suma los elementos impares.
5.	Emite mensaje de cada elemento que sea primo.


In [24]:
import numpy as np
import random as rd

#Funcion para encontrar números primos
def es_primo(num):
    if num <= 1: return False
    if num <= 3: return True
    if num % 2 == 0 or num % 3 == 0: return False
    i = 5
    while i * i <= num:
        if num % i == 0 or num % (i + 2) == 0: return False
        i += 6
    return True
def encontrar_primos(arr):
    return arr[np.vectorize(es_primo)(arr)]

#1 y 2
arreglo_1 = np.random.randint(0, 1001, size=10)
print("El arreglo inicial es: \n",arreglo_1)

#3
pares = arreglo_1 % 2 == 0
numpares = arreglo_1[pares]
numpares = len(numpares)
print("La cantidad de números pares es: \n",numpares)

#4
impares = arreglo_1 % 2 != 0
numimpares = arreglo_1[impares]
suma = np.sum(numimpares)
print("La suma de los números impares es: \n",suma)

#5

primos = encontrar_primos(arreglo_1)
print("Los números primos son: \n",primos)

El arreglo inicial es: 
 [269 833 979 830 213  99 386 314 998 928]
La cantidad de números pares es: 
 5
La suma de los números impares es: 
 2393
Los números primos son: 
 [269]


**Ejercicio 3:**  

Instrucciones específicas:
1.	Crear dos arreglos unidimensionales con nombre A y B y de tamaño 10, con elementos aleatorios de números enteros del 0 al 300.
2.	Muestra por pantalla la suma de los elementos de cada arreglo.
3.	Muestra por pantalla la suma de los elementos de ambos arreglos.
4.	Muestra por pantalla la tabla de multiplicar de los elementos impares del arreglo B.



In [29]:
import numpy as np
import random as rd

aregloA = np.random.randint(0, 301, size=10)
aregloB = np.random.randint(0, 301, size=10)

print("El arreglo A es: \n",aregloA)
print("El arreglo B es: \n",aregloB)

sumaA = np.sum(aregloA)
sumaB = np.sum(aregloB)

print("La suma de los elementos del arreglo A es: \n",sumaA)
print("La suma de los elementos del arreglo B es: \n",sumaB)

sumaAB = sumaA + sumaB
print("La suma de los elementos de ambos arreglos es: \n",sumaAB)

impares = aregloB % 2 != 0
numimpares = aregloB[impares]
print("Los números impares del arreglo B son: \n",numimpares)

for num in numimpares:
    for i in range(1, 11):
        print(num, "x", i, "=", num * i)

El arreglo A es: 
 [239  27 289 101 204 277 140 152 180 141]
El arreglo B es: 
 [231 117 192 286 220 208 107 161 200 275]
La suma de los elementos del arreglo A es: 
 1750
La suma de los elementos del arreglo B es: 
 1997
La suma de los elementos de ambos arreglos es: 
 3747
Los números impares del arreglo B son: 
 [231 117 107 161 275]
231 x 1 = 231
231 x 2 = 462
231 x 3 = 693
231 x 4 = 924
231 x 5 = 1155
231 x 6 = 1386
231 x 7 = 1617
231 x 8 = 1848
231 x 9 = 2079
231 x 10 = 2310
117 x 1 = 117
117 x 2 = 234
117 x 3 = 351
117 x 4 = 468
117 x 5 = 585
117 x 6 = 702
117 x 7 = 819
117 x 8 = 936
117 x 9 = 1053
117 x 10 = 1170
107 x 1 = 107
107 x 2 = 214
107 x 3 = 321
107 x 4 = 428
107 x 5 = 535
107 x 6 = 642
107 x 7 = 749
107 x 8 = 856
107 x 9 = 963
107 x 10 = 1070
161 x 1 = 161
161 x 2 = 322
161 x 3 = 483
161 x 4 = 644
161 x 5 = 805
161 x 6 = 966
161 x 7 = 1127
161 x 8 = 1288
161 x 9 = 1449
161 x 10 = 1610
275 x 1 = 275
275 x 2 = 550
275 x 3 = 825
275 x 4 = 1100
275 x 5 = 1375
275 x 6 = 16